# -*- coding: utf-8 -*-
"""86(272374).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n97tOsoMbAY6h-w_rXNH4lp9AFn34fT0

## Collect data
"""

github_list = '''https://github.com/GwLewis369/Hand-written-digit-classification-data.git
https://github.com/gbaonr/CS114_handwritten_digits_data
https://github.com/adamwhite625/CS114_hand_written_digit.git
https://github.com/theRaven1312/CS114.P21
https://github.com/Khoiisme1905/CS114.git
https://github.com/ProjectHT1/machinelearning
https://github.com/Searching96/hand-written-digit.git
https://github.com/Salmon1605/CS114
https://github.com/anhtuann1224/hand_written_digit
https://github.com/NATuanAN/Hand_written_digit_classification_data.git
https://github.com/huapogba/may-hoc
https://github.com/hieutran890j2/CS114.git
https://github.com/votanhoang483/CS114.P21-Hand_written_digit_classification
https://github.com/DHPh/CS114_hand_written_digit/
https://github.com/thaituanUIT/ReminiScenceAI
https://github.com/anngyn/CS114-Hand-Written-Digit
https://github.com/lngphgthao/cs114-hand-written-digit-classification/tree/main/hand_written_digit
https://github.com/Toan02Ky-UIT/CS114
https://github.com/Lochke/CS114_Handwritten_Digit_Classification.git
https://github.com/NThong325/CS114/tree/cfd654a14dd471f5272387139d586ddcbf9cdf7e/hand_written_digit
https://github.com/toanlamdata/digit-recognition-group
https://github.com/Nohenshin/CS114.P21-2025-
https://github.com/hmcslearning/ML1142025
https://github.com/lngphgthao/cs114-hand-written-digit-classification
https://github.com/huapogba/may-hoc
https://github.com/NThong325/CS114/tree/main/hand_written_digit
https://github.com/23520276/Hand-written-digit-classification/
https://github.com/NThong325/CS114
'''

from google.colab import drive
drive.mount('/gdrive')
data_dir = '/gdrive/MyDrive/ChauNguyen12/MNIST'

# Commented out IPython magic to ensure Python compatibility.
# %cd $data_dir
!git config --global core.compression 0
!rm -rf $data_dir/*
for i in github_list.split():
  # !echo $i
  # !git clone $i
  dir_name = !echo "$i" | sed -E 's|https://github.com/([^/]+)/([^/]+)(\.git)?|\1_\2|'
  dir_name = dir_name[0]
  # print(dir_name[0])
  !git clone $i /tmp/$dir_name || rm -rf /tmp/$dir_name
  !mv /tmp/$dir_name $data_dir/$dir_name
  # !echo $dir_name
  # !git clone $i

!ls */hand_written_digit/??52????/

!ls $data_dir | wc -l
print(len(github_list.split()))

"""## Thống kê số lượng"""

from google.colab import drive
drive.mount('/gdrive')
data_dir = '/gdrive/MyDrive/ChauNguyen12/MNIST'

!ls $data_dir/huapogba_may-hoc/hand_written_digit

import glob
import os
from tabulate import tabulate

image_folders = glob.glob(f'{data_dir}/*/hand_written_digit/??52????')
image_lists = []
table = []

for folder in image_folders:
    mssv = os.path.basename(folder)
    row = [mssv]
    total = 0
    for i in range(10):
        imgs = glob.glob(f'{folder}/{i}_*')
        image_lists.extend(imgs)
        row.append(len(imgs))
        total += len(imgs)
    row.append(total)
    table.append(row)

headers = ['MSSV'] + list(range(10)) + ['Sum']
print(tabulate(table, headers=headers))
print(f"Tổng số ảnh: {len(image_lists)}")

"""## Prepare dataset"""

!pip install pyheif pillow-heif

from google.colab import drive
drive.mount('/gdrive')
data_dir = '/gdrive/MyDrive/ChauNguyen12/MNIST'

from PIL import Image
import os
from tqdm import tqdm
import pillow_heif
pillow_heif.register_heif_opener()

root_dir = '/gdrive/MyDrive/ChauNguyen12/MNIST'
for label_folder in os.listdir(root_dir):
    folder_path = os.path.join(root_dir, label_folder)
    for filename in tqdm(os.listdir(folder_path), desc=f"Checking {label_folder}"):
        img_path = os.path.join(folder_path, filename)
        try:
            img = Image.open(img_path)
            if img.mode != 'RGB':
                print(f"Converting: {img_path} from {img.mode} to RGB")
                img.convert('RGB').save(img_path)  # Ghi đè
        except Exception as e:
            print(f"Error with file {img_path}: {e}")

import torch
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import pyheif
import io
import random

class DigitDataset(Dataset):
    def __init__(self, image_paths, transform=None):
        self.image_paths = image_paths
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        label = int(os.path.basename(img_path)[0])

        try:
            if img_path.lower().endswith(".heic"):
                heif_file = pyheif.read(img_path)
                image = Image.open(io.BytesIO(heif_file.data))
            else:
                image = Image.open(img_path)
        except:
            image = Image.new("RGB", (64, 64))

        image = image.convert("RGB")

        if self.transform:
            image = self.transform(image)

        return image, label

# Data augmentation và chuẩn hóa
transform = transforms.Compose([
    transforms.Resize((64, 64)),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.5]*3, [0.5]*3)
])

random.shuffle(image_lists)
split = int(0.9 * len(image_lists))
train_paths = image_lists[:split]
test_paths = image_lists[split:]

train_dataset = DigitDataset(train_paths, transform=transform)
test_dataset = DigitDataset(test_paths, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

"""### Build model"""

class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, 3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(128 * 8 * 8, 256)
        self.fc2 = nn.Linear(256, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = x.view(-1, 128 * 8 * 8)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

"""### Training"""

# Huấn luyện mô hình
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = CNN().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
criterion = nn.CrossEntropyLoss()

num_epochs = 30
train_acc_list = []
test_acc_list = []

for epoch in range(num_epochs):
    model.train()
    correct = total = 0
    for images, labels in tqdm(train_loader):
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    train_acc = correct / total
    train_acc_list.append(train_acc)

    model.eval()
    correct = total = 0
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    test_acc = correct / total
    test_acc_list.append(test_acc)

    print(f"Epoch {epoch+1}/{num_epochs}, Train Acc: {train_acc:.4f}, Test Acc: {test_acc:.4f}")

model_path = '/gdrive/MyDrive/ChauNguyen12/MNIST/trained_model.pth'
torch.save(model.state_dict(), model_path)
print(f"Model saved to {model_path}")

# Khởi tạo mô hình mới với cùng kiến trúc
loaded_model = CNN()
loaded_model.load_state_dict(torch.load(model_path))
loaded_model.to(device)
loaded_model.eval()  # Rất quan trọng để chuyển sang chế độ inference

!pip install -U gdown

import gdown

# Link chia sẻ Google Drive -> phải đổi sang dạng "uc?id="
file_id = "1UhMPzU-84KYH1-ujisJj08kb4Ji7gBLe"
url = f"https://drive.google.com/uc?id={file_id}"

# Nơi lưu tệp tải về
output = "/content/10000_images.zip"

# Tải về
gdown.download(url, output, quiet=False)

import zipfile

with zipfile.ZipFile("/content/10000_images.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/10000_images")

print("Đã giải nén xong.")

!pip install pillow-heif

import os
from PIL import Image, UnidentifiedImageError
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader
import torch
import pandas as pd

# Hỗ trợ HEIC
import pillow_heif
pillow_heif.register_heif_opener()

from torch.utils.data import Dataset
from PIL import Image

class InferenceImageDataset(Dataset):
    def __init__(self, image_paths, transform=None):
        self.transform = transform
        self.valid_samples = []

        for path in image_paths:
            try:
                with Image.open(path) as img:
                    img.convert("RGB")
                self.valid_samples.append(path)
            except Exception as e:
                print(f"Bỏ ảnh lỗi: {path} ({e})")

    def __len__(self):
        return len(self.valid_samples)

    def __getitem__(self, idx):
        path = self.valid_samples[idx] # Get the path from the list of valid samples
        image = Image.open(path).convert("RGB")
        if self.transform:
            image = self.transform(image)
        return image, path # Return the image and its path

def is_image_file(filename):
    image_extensions = {
        '.jpg', '.jpeg', '.png', '.bmp', '.gif', '.tiff', '.webp',
        '.jfif', '.pjpeg', '.pjp', '.svg', '.ico', '.heic', '.raw'
    }
    return os.path.splitext(filename)[1].lower() in image_extensions

image_dir = "/content/10000_images"
image_paths = []

for root, _, files in os.walk(image_dir):
    for file in files:
        if is_image_file(file):
            image_paths.append(os.path.join(root, file))

print(f"Tổng số ảnh tìm được: {len(image_paths)}")

transform = transforms.Compose([
    transforms.Resize((64, 64)),  # cần đúng
    transforms.ToTensor()
])

dataset = InferenceImageDataset(image_paths, transform=transform)
print(f"Số ảnh hợp lệ sau lọc: {len(dataset)}")

inference_loader = DataLoader(dataset, batch_size=64, shuffle=False)

import torch
import torch.nn as nn
import torch.nn.functional as F

class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, 3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(128 * 8 * 8, 256)
        self.fc2 = nn.Linear(256, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = x.view(-1, 128 * 8 * 8)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model_path = '/gdrive/MyDrive/ChauNguyen12/MNIST/trained_model.pth'
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = CNN().to(device)
model.load_state_dict(torch.load(model_path, map_location=device))
model.eval()

print("✅ Mô hình đã được load thành công.")

import os
import torch

model.eval()
results = []

with torch.no_grad():
    for images, paths in inference_loader:
        images = images.to(device)
        outputs = model(images)
        predicted = torch.argmax(outputs, dim=1).cpu().numpy()
        for label, path in zip(predicted, paths):
            filename = os.path.basename(path).strip()
            results.append((filename, int(label)))

# Ghi ra file
output_file = "/content/final_results.csv"
with open(output_file, "w") as f:
    for filename, label in results:
        f.write(f"{filename},{label}\n")

print("✅ Đã xử lý đúng 1 chuỗi ' -' trong tên file và lưu vào:", output_file)

from google.colab import files
files.download('/content/final_results.csv')